# Compiler
  CXX = g++
 
  # compiler flags:
  #  -g     - this flag adds debugging information to the executable file
  #  -Wall  - this flag is used to turn on most compiler warnings
  CXXFLAGS  = -g -Wall
 
  # The build target 
  TARGET = factoring
 
  all: $(TARGET)
 
  $(TARGET): $(TARGET).c
              $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).cpp
 
  clean:
              $(RM) $(TARGET)