CXX=g++
RM=rm -f
CPPFLAGS=-std=c++17 -lstdc++fs
srcfiles = ./src/FactoringCommonText.cc
executable=Factoringcommontext
obj=Factoringcommontext.o

Factoringcommontext: $(srcfiles)
	$(CXX) $(CPPFLAGS) -o $(executable) $(srcfiles) -I.

.PHONY: clean

clean:
	$(RM) -f $(obj) $(executable)